local Util

describe("LibUtil", function()
	setup(function()
		loadfile("Test/TestSetup.lua")(false, 'LibUtil')
		loadfile("Libs/LibUtil-1.2/Test/BaseTest.lua")()
		LoadDependencies()
		ConfigureLogging()
		Util = LibStub:GetLibrary('LibUtil-1.2')
	end)

	teardown(function()
		After()
	end)

	describe('Bitfield', function()
		it("does the needful", function()
			local bf = Util.Bitfield.Create()
			assert.equal('00', tostring(bf))
			bf = Util.Bitfield.CreateAndEnableBits(1, 3, 7)
			assert.equal('01000101', tostring(bf))
			assert(bf:BitEnabled(1))
			assert(bf:BitDisabled(5))
			bf:ToggleBits(3)
			assert(bf:BitDisabled(3))
			assert(bf:BitEnabled(1))
			assert(bf:BitEnabled(7))
			assert.equal('01000001', tostring(bf))
		end)
	end)
end)